### PR TITLE
 add handling for empty array, and to prevent invalid type

### PR DESCRIPTION
**Pull request by ghost**
Hi Michael,

using this module, I ran into the situation of sending an empty array, and built a fix to handle this.

in this context I also added a fix for an invalid type, plus a fix for the git url in the package.json.

Regards
  Stefan

### CODE REVIEW

**Comment by mshick** [comment]
@stefanheine This is just a branch I made of the repo that was published to npm. I'm not sure what happened to the original, I see that the git repo is gone.

I've made a number of local changes, and if you're interested, maybe we can create a new project together providing this functionality?

**Comment by transitive-bullshit** [comment]
Hey, sorry guys -- the company behind the initial repo, Vidy, has some internal issues and pulled the original github repo.  Very sorry for the confusion, as I had no control over the mess.

I'd be very glad to make this the official branch and publish a new version to npm if everyone's onboard.

Cheers!

**Comment by mshick** [comment]
@fisch0920 Sure, I can make you a collaborator, also happy to just transfer ownership to you. Let me know which approach you prefer.

I believe as it was I encountered some issues with the module related to build / packaging. Maybe we can work out a system to get support back to node v4. I have some previous work I can apply.

**Comment by transitive-bullshit** [comment]
Would love it if you transferred over to me and I'll add you as a collaborator.  Didn't want to presume too much ;-)

Yeah, node v4 is definitely possible; for reference, I've personally switched over to using https://github.com/sindresorhus/promise-fun and p-map, in particular, as @sindresorhus's set of utils is much more comprehensive and targets Promises in general, in stead of async await specifically.

**Comment by mshick** [comment]
@fisch0920 transferred.

Interesting to know about p-map, thanks for the tip.

**Review by transitive-bullshit — APPROVED** [review]

**Comment by transitive-bullshit** [comment]
@stefanheine @mshick thanks, guys! Will publish a new version shortly.

**Comment by ghost** [comment]
Folks, thanks for the quick action and positive response.

I had come to this module, as we're just switching to node 8 with async/await and I was looking for a simple replacement of functionality like http://caolan.github.io/async/docs.html#eachLimit .

**Comment by ghost** [comment]
Hi, any idea no when the update would show in npm?

**Pull request merged**
